### ISSUE TITLE
Can I use this with Gira X1?

### ISSUE THREAD

**Issue by StefanOltmann** [pitschr/knx-link#76]
Currently I have a OpenHAB setup with a KNXD service as KNX router that communicates with my Gira X1.

I did not manage to make it work otherwise back then.

Can knx-link use Gira X1 directly without a KNX router in between?
If so: How can I configure that?

I don't see how I can set my KNX addr 1.1.55 for example.

Automatic discovery seems not to work with Gira X1:
```
    val groupAddress = GroupAddress.of(2, 1, 0)

    DefaultKnxClient.createStarted().use { client ->

        client.writeRequest(groupAddress, DPT1.SWITCH.of(false))
    }
```
```
Exception in thread "main" li.pitschmann.knx.core.exceptions.KnxDiscoveryNotReceivedException: Could not get discovery from KNX Net/IP device: request=SearchRequestBody{discoveryEndpoint=HPAI{length=8 (0x08), protocol=HostProtocol{name=IPV4_UDP, friendlyName=IP v4 UDP communication, code=1 (0x01)}, address=0.0.0.0 (0x00 00 00 00), port=3671 (0x0E 57)}, rawData=0x08 01 00 00 00 00 0E 57}, response=<null>
	at li.pitschmann.knx.core.communication.InternalKnxClient.fetchDiscoveryFromKNX(InternalKnxClient.java:539)
	at li.pitschmann.knx.core.communication.InternalKnxClient.startTunneling(InternalKnxClient.java:165)
	at li.pitschmann.knx.core.communication.InternalKnxClient.start(InternalKnxClient.java:125)
	at li.pitschmann.knx.core.communication.DefaultKnxClient.createStarted(DefaultKnxClient.java:78)
	at li.pitschmann.knx.core.communication.DefaultKnxClient.createStarted(DefaultKnxClient.java:66)
	at li.pitschmann.knx.core.communication.DefaultKnxClient.createStarted(DefaultKnxClient.java:49)
	at MainKt.main(main.kt:9)
Caused by: java.lang.NullPointerException: No search response received for request: SearchRequestBody{discoveryEndpoint=HPAI{length=8 (0x08), protocol=HostProtocol{name=IPV4_UDP, friendlyName=IP v4 UDP communication, code=1 (0x01)}, address=0.0.0.0 (0x00 00 00 00), port=3671 (0x0E 57)}, rawData=0x08 01 00 00 00 00 0E 57}
	at li.pitschmann.knx.core.utils.Preconditions.checkNonNull(Preconditions.java:63)
	at li.pitschmann.knx.core.communication.InternalKnxClient.fetchDiscoveryFromKNX(InternalKnxClient.java:535)
	... 6 more

```
---

And giving the IP adress of Gira X1 results also in an exception:
```
    val groupAddress = GroupAddress.of(2, 1, 0)

    DefaultKnxClient.createStarted("192.168.0.2").use { client ->

        client.writeRequest(groupAddress, DPT1.SWITCH.of(false))
    }
```
```
Exception in thread "main" li.pitschmann.knx.core.exceptions.KnxDescriptionNotReceivedException: Could not get description from KNX Net/IP device: DescriptionRequestBody{controlEndpoint=HPAI{length=8 (0x08), protocol=HostProtocol{name=IPV4_UDP, friendlyName=IP v4 UDP communication, code=1 (0x01)}, address=0.0.0.0 (0x00 00 00 00), port=0 (0x00)}, rawData=0x08 01 00 00 00 00 00 00}
	at li.pitschmann.knx.core.communication.InternalKnxClient.fetchDescriptionFromKNX(InternalKnxClient.java:503)
	at li.pitschmann.knx.core.communication.InternalKnxClient.verifyTunnelingSupport(InternalKnxClient.java:192)
	at li.pitschmann.knx.core.communication.InternalKnxClient.startTunneling(InternalKnxClient.java:173)
	at li.pitschmann.knx.core.communication.InternalKnxClient.start(InternalKnxClient.java:125)
	at li.pitschmann.knx.core.communication.DefaultKnxClient.createStarted(DefaultKnxClient.java:78)
	at li.pitschmann.knx.core.communication.DefaultKnxClient.createStarted(DefaultKnxClient.java:66)
	at MainKt.main(main.kt:9)
```

---

My knxd.ini looks like this:
```
[A.tcp]
server = knxd_tcp
systemd-ignore = true

[B.ipt]
driver = ipt
ip-address = 192.168.0.2

[debug-server]
name = mcast:knxd

[main]
addr = 1.1.55
background = true
client-addrs = 1.1.56:1
connections = server,A.tcp,B.ipt
#systemd = systemd

[server]
debug = debug-server
discover = true
router = router
server = ets_router
tunnel = tunnel
```

And this is my OpenHAB knx.cfg:
```
ip=224.0.23.12
ignorelocalevents=true
type=TUNNEL
localIp=192.168.0.3
busaddr=1.1.56
port=3671
readRetries=1
```
---
Calimero-project discovery does find my Gira X1:
```
eth2 /192.168.0.60 <=> 192.168.0.2:3671 (IPv4 UDP) "Gira X1"
	KNX address 1.1.50
	KNX medium TP1
	Installation 0 - Project 0 (ID 0)
	KNX IP multicast address 224.0.23.12
	MAC address ---snip---
	S/N ---snip---
	Core (v1)
	Device Management (v2)
	Tunneling (v1)
	Remote Configuration/Diagnosis (v1)
```

**Comment by pitschr** [comment]
Hello Stefan.

Unfortunately, I do not have Gira X1, but I was in assumption that it should work for all KNX interface / routers, as I implemented according to the KNX specification. I only have MDT IP Router and WireGate which also accepts KNX traffic via EIBD. Therefore it should be work with Gira X1 as well, at least from theory point of view.

Do you have the ability to enable WireShark (or tcpdump) to interspect if there are some ingoing / outgoing traffics at all when you execute your application. Given exception it sounds the Java Runtime is not able to communicate with Gira X1 for some reasons.

I would suggest to tackle the issue with the tunneling first (and the discovery afterwards). When I understand correctly then Gira X1 is an IP interface. Please make sure that your IP interface still allows one more connection. Setting KNX address `1.1.55` is not required for the knx-link, because that should be returned by your KNX device as part of description frame. The KNX address is, however, not required for the communication over UDP.

When I understand correctly, then your Gira X1 has IP Address `192.168.0.2` and assuming your KNX group address for switch on/off the lamp would be `2.1.0`. Let's start with the NAT enabled (3rd argument of ConfigBuilder#tunneling method):

```
public final class LampOnExample {
    public static void main(final String[] args) {
        // this is the group address where the KNX actuator listens to switch on/off a lamp
        final var groupAddress = GroupAddress.of(2, 1, 0); 

        // use tunneling with NAT = true
        final var config = ConfigBuilder.tunneling(Networker.getByAddress(192, 168, 0, 2), CoreConfigs.KNX_PORT, true).build();

        try (final var client = DefaultKnxClient.createStarted(config)) {
            client.writeRequest(groupAddress, DPT1.SWITCH.of(true));  // true = lamp will be on, false = lamp will be off
        }
        // auto-closed and disconnected by KNX client
    }
}
```

Your log file should show lines like (given communication was done with WireGate and EIBD):

```
... lines omitted ...
2020-11-25 19:04:20,323 [DEBUG] [l.p.k.c.c.queue.DefaultOutboxQueue] - Sending packet: DescriptionRequestBody{controlEndpoint=HPAI{length=8 (0x08), protocol=HostProtocol{name=IPV4_UDP, friendlyName=IP v4 UDP communication, code=1 (0x01)}, address=0.0.0.0 (0x00 00 00 00), port=0 (0x00)}, rawData=0x08 01 00 00 00 00 00 00}
2020-11-25 19:04:20,327 [DEBUG] [l.p.k.c.c.queue.DefaultOutboxQueue] - SEND: DESCRIPTION_REQUEST
----------------------------------------------------------------
   Source:  /192.168.1.18:57412
   Target:  /192.168.1.29:3671
   Raw:     0x06 10 02 03 00 0E 08 01 00 00 00 00 00 00
   Header:  Header{length=6 (0x06), protocolVersion=16 (0x10), serviceType=ServiceType{name=DESCRIPTION_REQUEST, friendlyName=Description Request, code=515 (0x02 03), family=ServiceTypeFamily{name=CORE, friendlyName=KNX/IP Core, code=2 (0x02)}, responseIdentifier=DESCRIPTION_RESPONSE}, totalLength=14 (0x0E), rawData=0x06 10 02 03 00 0E}
   Body:    DescriptionRequestBody{controlEndpoint=HPAI{length=8 (0x08), protocol=HostProtocol{name=IPV4_UDP, friendlyName=IP v4 UDP communication, code=1 (0x01)}, address=0.0.0.0 (0x00 00 00 00), port=0 (0x00)}, rawData=0x08 01 00 00 00 00 00 00}
----------------------------------------------------------------
... lines omitted ...
```

and the response should look like 

```
... lines omitted ...
2020-11-25 19:04:20,444 [DEBUG] [l.p.k.c.c.queue.DefaultInboxQueue] - RECEIVE: DESCRIPTION_RESPONSE
----------------------------------------------------------------
   Source: /192.168.1.29:3671
   Target: /192.168.1.18:57412
   Raw:    0x06 10 02 04 00 44 36 01 02 00 00 00 00 00 10 06 56 09 0B 00 E0 00 17 0C 00 00 00 00 00 00 65 69 62 64 20 6F 6E 20 57 69 72 65 47 61 74 65 00 00 00 00 00 00 00 00 00 00 00 00 00 00 08 02 02 01 03 01 04 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
   Header: Header{length=6 (0x06), protocolVersion=16 (0x10), serviceType=ServiceType{name=DESCRIPTION_RESPONSE, friendlyName=Description Response, code=516 (0x02 04), family=ServiceTypeFamily{name=CORE, friendlyName=KNX/IP Core, code=2 (0x02)}, responseIdentifier=}, totalLength=68 (0x44), rawData=0x06 10 02 04 00 44}
   Body:   DescriptionResponseBody{deviceHardwareInformation=DeviceHardwareInformationDIB{length=54 (0x36), descriptionType=DescriptionType{name=DEVICE_INFO, friendlyName=Device information, code=1 (0x01)}, mediumType=MediumType{name=TP, friendlyName=Twisted Pair 1 (9600bit/s), code=2 (0x02)}, programmingMode=false, individualAddress=IndividualAddress{addressType=AddressType{name=INDIVIDUAL, friendlyName=Individual Address, code=0 (0x00)}, address=0.0.0}, projectNumber=0, projectInstallationIdentifier=0, serialNumber=0x10 06 56 09 0B 00, multicastAddress=224.0.23.12, macAddress=00:00:00:00:00:00, deviceFriendlyName=eibd on WireGate}, supportedDeviceFamilies=SupportedDeviceFamiliesDIB{length=8 (0x08), descriptionType=DescriptionType{name=SUPPORTED_SERVICE_FAMILIES, friendlyName=Supported Service Families, code=2 (0x02)}, serviceFamilies=[ServiceTypeFamilyVersion{family=ServiceTypeFamily{name=CORE, friendlyName=KNX/IP Core, code=2 (0x02)}, version=1}, ServiceTypeFamilyVersion{family=ServiceTypeFamily{name=DEVICE_MANAGEMENT, friendlyName=KNX device Management, code=3 (0x03)}, version=1}, ServiceTypeFamilyVersion{family=ServiceTypeFamily{name=TUNNELING, friendlyName=KNX/IP Tunneling, code=4 (0x04)}, version=1}]}, ipConfig=null, ipCurrentConfig=null, knxAddresses=null, manufacturerData=null, rawData=0x36 01 02 00 00 00 00 00 10 06 56 09 0B 00 E0 00 17 0C 00 00 00 00 00 00 65 69 62 64 20 6F 6E 20 57 69 72 65 47 61 74 65 00 00 00 00 00 00 00 00 00 00 00 00 00 00 08 02 02 01 03 01 04 01}
----------------------------------------------------------------
... lines omitted ...
```

Questions:
* Are you running the application in a container (e.g. docker, podman, ...)?
* Do you see incoming / outgoing traffic using e.g. WireShark / tcpdump?
* Do you see a difference with NAT enabled? (NAT is disabled per default)

**Comment by StefanOltmann** [comment]
Hello Christoph,

thank you for your answer.

Gira X1 is a "mini server" for a smart home with logic module, visualisation and so on and has a KNX IP Interface integrated.

In the mean time I figured out that calimero-project works together with Gira X1.
See here for a working sample: https://github.com/StefanOltmann/StefansSmartHomePreview/blob/master/server/src/main/kotlin/de/stefan_oltmann/smarthome/server/knx/KnxService.kt

I run this code locally out of IDEA.

Executing your provided LampOnExample I get two new Exceptions that seem to be much closer to the root of the problem:

```
li.pitschmann.knx.core.exceptions.KnxEnumNotFoundException: Could not find enum for class 'li.pitschmann.knx.core.dib.ServiceTypeFamily' and code: 7
	at li.pitschmann.knx.core.dib.ServiceTypeFamily.lambda$valueOf$1(ServiceTypeFamily.java:68)
	at java.base/java.util.Optional.orElseThrow(Optional.java:401)
```

and 

```
Exception in thread "main" li.pitschmann.knx.core.exceptions.KnxDescriptionNotReceivedException: Could not get description from KNX Net/IP device: DescriptionRequestBody{controlEndpoint=HPAI{length=8 (0x08), protocol=HostProtocol{name=IPV4_UDP, friendlyName=IP v4 UDP communication, code=1 (0x01)}, address=0.0.0.0 (0x00 00 00 00), port=0 (0x00)}, rawData=0x08 01 00 00 00 00 00 00}
	at li.pitschmann.knx.core.communication.InternalKnxClient.fetchDescriptionFromKNX(InternalKnxClient.java:503)
	at li.pitschmann.knx.core.communication.InternalKnxClient.verifyTunnelingSupport(InternalKnxClient.java:192)

```

I could not figure out what service type 7 should be.

Here is the [full log](https://github.com/pitschr/knx-link/files/5599191/full_log.txt).

As requested here also the [wireshark log](https://github.com/pitschr/knx-link/files/5599229/wireshark_log.txt).

I hope this helps. :)

**Comment by pitschr** [comment]
Thanks! I re-checked the KNX Specification and, yes, I forgot to add 3 service families: 
* KNX/IP Remote Logging
* KNX/IP Remote Configuration and Diagnosis
* KNX/IP Object Server

The one that is returned by your Gira X1 was the missing one: KNX/IP Remote Configuration and Diagnosis 

I have raised a Pull Request. Can you please verify if that would fix your issue or if you are encountering other issues?

**Comment by StefanOltmann** [comment]
Building it locally failed.

```
Some problems were encountered while building the effective model for li.pitschmann:knx-logic:jar:0.0.4-SNAPSHOT
'build.plugins.plugin.version' for org.apache.maven.plugins:maven-deploy-plugin is missing. @ line 55, column 21
Some problems were encountered while building the effective model for li.pitschmann:knx-examples:jar:0.0.4-SNAPSHOT
'build.plugins.plugin.version' for org.apache.maven.plugins:maven-deploy-plugin is missing. @ line 99, column 21
It is highly recommended to fix these problems because they threaten the stability of your build.
For this reason, future Maven versions might no longer support building such malformed projects.
```

Can you provide artifacts or push it directly to maven central? :)

**Comment by pitschr** [comment]
Reopening this ticket as the ticket has been automatically closed due merge of #77 .

Anyway, I deployed 0.0.4 to Maven repository, it will take some time and should appear then. Please let me know if that works. Thank you.

**Comment by pitschr** [comment]
Additionally, can you please share which tests are failing on your machine (and what exactly)? I'm curious and if and how I may fix that. The warning with MapsTest can be safely ignored - it is just using a dirty hack. Have not found a clean way at this time.

**Comment by StefanOltmann** [comment]
> 
> 
> Additionally, can you please share which tests are failing on your machine (and what exactly)? I'm curious and if and how I may fix that. The warning with MapsTest can be safely ignored - it is just using a dirty hack. Have not found a clean way at this time.

I found your SleeperTest to be a flipping Unit Test.
Sometimes it runs, sometimes it fails.

I know from my own experience that testing such things is always hard.
At my projects those tests usually fail if the build server is under heavy load. ;)

```
[ERROR] Tests run: 7, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 0.682 s <<< FAILURE! - in li.pitschmann.knx.core.utils.SleeperTest
[ERROR] testNoInterrupt  Time elapsed: 0.064 s  <<< FAILURE!
java.lang.AssertionError: 
Expecting:
  <145L>
to be close to:
  <100L>
by less than 10% but difference was 45.0%.
(a difference of exactly 10% being considered valid)
	at li.pitschmann.knx.core.utils.SleeperTest.lambda$testNoInterrupt$0(SleeperTest.java:53)
	at li.pitschmann.knx.core.utils.SleeperTest.assertUpToThreeTimes(SleeperTest.java:186)
	at li.pitschmann.knx.core.utils.SleeperTest.testNoInterrupt(SleeperTest.java:45)
[ERROR] testSleepWithPredicateAlwaysFalse  Time elapsed: 0.38 s  <<< FAILURE!
java.lang.AssertionError: 
Expecting:
  <111L>
to be close to:
  <100L>
by less than 10% but difference was 11.0%.
(a difference of exactly 10% being considered valid)
	at li.pitschmann.knx.core.utils.SleeperTest.lambda$testSleepWithPredicateAlwaysFalse$4(SleeperTest.java:90)
	at li.pitschmann.knx.core.utils.SleeperTest.assertUpToThreeTimes(SleeperTest.java:186)
	at li.pitschmann.knx.core.utils.SleeperTest.testSleepWithPredicateAlwaysFalse(SleeperTest.java:82)
```

**Comment by StefanOltmann** [comment]
It works!
Also with and without NAT.

Nice. knx-link is now officially Gira X1 compatible. ;)

**Comment by pitschr** [comment]
Danke!

Ah yes ... the SleeperTest ... a nasty one. That is also why I added #assertUpToThreeTimes to this test suite resulting that failure rate has almost eliminated on my machine (MacOS) and travis-ci.com. For Windows it must probably be more tolerant or use a higher timeout. Good to know it and I should probably check with a windows machine too.
