### ISSUE TITLE
KnxEnumNotFoundException

### ISSUE THREAD

**Issue by StefanOltmann** [pitschr/knx-link#98]
The service was running fine for about 3 days now. 

Then it started to spam "`Event already acknowledged?`" for about 2 days, but was still functional.

Now the service stopped itself (due to the error?) with an `KnxEnumNotFoundException`.

```
2021-01-20 12:57:26,402 INFO [eventLoopGroupProxy-4-1] [Application.kt:194] [API] | SET schlafzimmer_rolladen TO 80%
2021-01-20 12:57:26,417 WARN [Thread-117486] [TunnelingAckTask.java:54] Event already acknowledged? Looks there was a communication problem. Ignoring acknowledge: TunnelingAckBody{length=4 (0x04), channelId=2 (0x02), sequence=60 (0x3C), status=Status{name=E_NO_ERROR, friendlyName=Operation successful, code=0 (0x00)}, rawData=0x04 02 3C 00} for event: KnxSingleEvent{requestEvent=RequestEvent{requestTime=2021-01-20T11:57:26.408738Z, request=TunnelingRequestBody{length=4 (0x04), channelId=2 (0x02), sequence=60 (0x3C), cemi=CEMI{messageCode=MessageCode{name=L_DATA_REQ, friendlyName=L-Data.req (Request), code=17 (0x11)}, additionalInfo=AdditionalInfo{length=0, totalLength=1, rawData=0x00}, controlByte1=ControlByte1{standardFrame=true, repeatEnabled=false, broadcastType=BroadcastType{name=NORMAL, friendlyName=Normal Broadcast, code=1 (0x01)}, priority=Priority{name=LOW, friendlyName=Low Priority, code=3 (0x03)}, requestAcknowledge=false, errorConfirmation=false, rawData=0xBC}, controlByte2=ControlByte2{addressType=AddressType{name=GROUP, friendlyName=Group Address, code=1 (0x01)}, hopCount=6 (0x06), extendedFrameFormat=0 (0x00), rawData=0xE0}, sourceAddress=IndividualAddress{addressType=AddressType{name=INDIVIDUAL, friendlyName=Individual Address, code=0 (0x00)}, address=0.0.0, rawData=0x00 00}, destinationAddress=GroupAddress{addressType=AddressType{name=GROUP, friendlyName=Group Address, code=1 (0x01)}, address=17156, address(2-level)=8/772, address(3-level)=8/3/4, rawData=0x43 04}, npduLength=2 (0x02), tpci=TPCI{name=UNNUMBERED_PACKAGE, friendlyName=UDT unnumbered package, code=0 (0x00)}, packetNumber=0 (0x00), apci=APCI{name=GROUP_VALUE_WRITE, friendlyName=Group Value Write, code=128..191 (0x80..0xBF)}, data=[-52] (0xCC)}, rawData=0x04 02 3C 00 11 00 BC E0 00 00 43 04 02 00 80 CC}}, responseEvent=ResponseEvent{responseTime=2021-01-15T18:06:13.654587Z, response=TunnelingAckBody{length=4 (0x04), channelId=2 (0x02), sequence=60 (0x3C), status=Status{name=E_NO_ERROR, friendlyName=Operation successful, code=0 (0x00)}, rawData=0x04 02 3C 00}}}
2021-01-20 13:31:25,042 ERROR [pool-10-thread-1] [AbstractKnxQueue.java:94] Error while processing KNX packets.
li.pitschmann.knx.core.exceptions.KnxEnumNotFoundException: Could not find enum for class 'li.pitschmann.knx.core.cemi.APCI' and code: 960
	at li.pitschmann.knx.core.cemi.APCI.lambda$valueOf$1(APCI.java:112)
	at java.base/java.util.Optional.orElseThrow(Optional.java:408)
	at li.pitschmann.knx.core.cemi.APCI.valueOf(APCI.java:112)
	at li.pitschmann.knx.core.cemi.CEMI.<init>(CEMI.java:145)
	at li.pitschmann.knx.core.cemi.CEMI.of(CEMI.java:180)
	at li.pitschmann.knx.core.body.TunnelingRequestBody.<init>(TunnelingRequestBody.java:85)
	at li.pitschmann.knx.core.body.TunnelingRequestBody.of(TunnelingRequestBody.java:95)
	at li.pitschmann.knx.core.body.BodyFactory.of(BodyFactory.java:93)
	at li.pitschmann.knx.core.body.BodyFactory.of(BodyFactory.java:72)
	at li.pitschmann.knx.core.body.BodyFactory.of(BodyFactory.java:57)
	at li.pitschmann.knx.core.communication.queue.AbstractInboxQueue.action(AbstractInboxQueue.java:88)
	at li.pitschmann.knx.core.communication.queue.AbstractKnxQueue.run(AbstractKnxQueue.java:79)
	at li.pitschmann.knx.core.utils.Executors$MdcRunnable.run(Executors.java:136)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at li.pitschmann.knx.core.utils.Executors$MdcRunnable.run(Executors.java:136)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2021-01-20 13:31:28,034 INFO [Thread-120079] [InternalKnxClient.java:274] Client will be stopped.
2021-01-20 13:31:28,045 INFO [pool-10-thread-2] [AbstractKnxQueue.java:104] *** END ***
2021-01-20 13:31:28,066 INFO [pool-10-thread-1] [AbstractKnxQueue.java:104] *** END ***
2021-01-20 13:31:28,068 INFO [Thread-120079] [InternalKnxClient.java:327] Channel Communicator stopped gracefully?: true
2021-01-20 13:31:28,069 INFO [Thread-120079] [InternalKnxClient.java:331] KNX Services stopped gracefully?: true
2021-01-20 13:31:28,069 INFO [pool-8-thread-2] [AbstractKnxQueue.java:104] *** END ***
2021-01-20 13:31:28,080 INFO [pool-8-thread-1] [AbstractKnxQueue.java:104] *** END ***
2021-01-20 13:31:28,192 INFO [Thread-120079] [InternalKnxClient.java:281] Plugin Manager closed.
```

**Comment by pitschr** [comment]
Lines like 
```
2021-01-20 12:57:26,417 WARN [Thread-117486] [TunnelingAckTask.java:54] Event already acknowledged? Looks there was a communication problem. Ignoring acknowledge: TunnelingAckBody{length=4 (0x04), cha... omitted ...
```

I guess I know where the problem was. Can you confirm that it started spamming after 256th request? Reason: The sequence number of KNX goes from 0..255, meaning, only up to 255 requests can be pooled. After 255 there will be a rollover (starting from 0 again). Here I may forget invoking a clearing flag.

Can you check your log file and confirm that is the case?

-----

Yes, the service has been stopped because the KNX client got an unsupported APCI code

```
li.pitschmann.knx.core.exceptions.KnxEnumNotFoundException: Could not find enum for class 'li.pitschmann.knx.core.cemi.APCI' and code: 960
```

960 is in binary: `11 1100 0000` which means you got a APCI which is reserved for the coupler only and in my understanding is not subject for KNX Net/IP communication according to the KNX Specification 3.3.7 (Application Layer, page 9)

Actually following are supported: 
* Group Value Read `00 0000 0000`
* Group Value Response `00 01nn nnnn` (n = for packets which are payload optimizable)
* Group Value Write `00 10nn nnnn` (n = for packets which are payload optimizable)
* Individual Address Write `00 1100 0000`
* Individual Address Read `01 0000 0000`
* Individual Address Write `01 0100 0000`

Can you figure out why you got this APCI and if it is relevant for the KNX Net/IP communication. I am not sure how I shall deal with that, but in worst case I can just make the `AbstractInboxQueue` implementation more robust and drop it as "error" to the plugins.

**Comment by pitschr** [comment]
Additional:
I have quickly checked `li.pitschmann.knx.core.communication.queue.AbstractKnxQueue#run` and it already contains the catch and notifies the plugin about the error.

```
                } catch (final Throwable e) {
                    log.error("Error while processing KNX packets.", e);
                    this.client.notifyError(new Throwable("Error while processing KNX packets.", e));
                    // proceed with next packet
                }
```

May I know what the Audit log said? Did you got a DISCONNECT_REQUEST ? I am wondering why the `InternalKnxClient#close()` has been initiated:

```
2021-01-20 13:31:28,034 INFO [Thread-120079] [InternalKnxClient.java:274] Client will be stopped.
```

and that was 3 seconds after the exception was thrown ... so it may not be related to the `KnxEnumNotFoundException` itself. Are you using your own plugin - if yes, do you have a logic there that may invoke the close method of the knx client?

**Comment by StefanOltmann** [comment]
> I guess I know where the problem was. Can you confirm that it started spamming after 256th request? Reason: The sequence number of KNX goes from 0..255, meaning, only up to 255 requests can be pooled. After 255 there will be a rollover (starting from 0 again). Here I may forget invoking a clearing flag.
> 
> Can you check your log file and confirm that is the case?

Most likely. I tested WIP smart home app a lot and it took a lot of messages to the same group address before that started to spam messages.

> Can you figure out why you got this APCI and if it is relevant for the KNX Net/IP communication.

> May I know what the Audit log said? Did you got a DISCONNECT_REQUEST ?

Unfortunately I run the service without the Audit plugin because I did not manage to get the logging working yet.

I use SLF4j v1.7.30 in front of logback classic v1.2.3.
This works fine, but as soon I add the audit plugin to the classpath I get an error message.
I saw that knx-link also uses SLF4j (in v1.7.29) and the current logback version.
So I got no idea right now there the problem is.

```
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#noProviders for further details.
SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions prior to 1.8.
SLF4J: Ignoring binding found at [jar:file:/C:/Users/Stefan/.m2/repository/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#ignoredBindings for an explanation.
```

> and that was 3 seconds after the exception was thrown ... so it may not be related to the `KnxEnumNotFoundException` itself. Are you using your own plugin - if yes, do you have a logic there that may invoke the close method of the knx client?

**Comment by StefanOltmann** [comment]
> I guess I know where the problem was. Can you confirm that it started spamming after 256th request? Reason: The sequence number of KNX goes from 0..255, meaning, only up to 255 requests can be pooled. After 255 there will be a rollover (starting from 0 again). Here I may forget invoking a clearing flag.
> 
> Can you check your log file and confirm that is the case?

Most likely. I tested WIP smart home app a lot and it took a lot of messages to the same group address before that started to spam messages.

> Can you figure out why you got this APCI and if it is relevant for the KNX Net/IP communication.

> May I know what the Audit log said? Did you got a DISCONNECT_REQUEST ?

Unfortunately I run the service without the Audit plugin because I did not manage to get the logging working yet.

I use SLF4j v1.7.30 in front of logback classic v1.2.3.
This works fine, but as soon I add the audit plugin to the classpath I get an error message.
I saw that knx-link also uses SLF4j (in v1.7.29) and the current logback version.
So I got no idea right now there the problem is.

```
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#noProviders for further details.
SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions prior to 1.8.
SLF4J: Ignoring binding found at [jar:file:/C:/Users/Stefan/.m2/repository/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#ignoredBindings for an explanation.
```

> and that was 3 seconds after the exception was thrown ... so it may not be related to the `KnxEnumNotFoundException` itself. Are you using your own plugin - if yes, do you have a logic there that may invoke the close method of the knx client?

Yes, you are right. There is a try-catch-Block which of course calls close() on any Exception. I will fix my code in the way that a new KnxClient will be created and used if the old one breaks due to exceptions - at least I assume that it's not safe to further use a KnxClient that threw an exception and may be in an undefined state.

**Comment by pitschr** [comment]
Hi.

I have added logic that response are now cleared when request is raised. The issue with spam should be gone then. The warning will still appear when your KNX Net/IP device sends an acknowledge packet which has not been requested. At least in theory it should not happen anymore. Let me know if you face it again.

You may try out https://github.com/pitschr/knx-link/tree/master-2021-01-21 and let me know if it is OK. I will also merge it later with https://github.com/pitschr/knx-link/tree/master-new-dpts branch which brings DPT25, 26 and few DPT sub types.

About SLF4J, I am not sure what the issue could be. Especially as the knx-core is also using the same SLF4J library. I don't see why it should be different for Audit Plugin. But the plugin is very useful for diagnosis, so I would recommend to try to include it.

The plugin that fetches the exception should not close the KNX client, because the KNX client is designed to stay robust and exceptions are subject to be ignored. The notification of exceptions are rather useful for e.g. auditing, statistic, ... . If you close the KnxClient then you have to restart the client again with the consequence that pools for event and status will be empty again.

**Comment by StefanOltmann** [comment]
Another dependency seems to upgrade SLF4j and casuses the problem.

I fixed that this way:
```
    // Logging
    implementation ("org.slf4j:slf4j-api") {
        version {
            strictly slf4jVersion
        }
    }
    implementation "ch.qos.logback:logback-classic:$logbackVersion"
    implementation "ch.qos.logback:logback-core:$logbackVersion"
```

Now I also run the audit plugin.

**Comment by pitschr** [comment]
Hi Stefan.

I am going to release version 0.3 soon (this month). May I know if you have encountered some issues meanwhile which could be fixed for upcoming version as well?

* New DPTs have been added (24, 25, 26, 27, 28 and 29)
* Several Sub DPTs (more than 20 Sub-DPTs) have been added as well based on most recent KNX specification
* DPT8.PERCENT now has only `double` for value while others have `int` as value
* Better error handling for DPTs and data integrity
* StepInterval (e.g. DPT3) is now a separate class, as it will be re-used by new DPTs + `StepInterval#parse(String)`
* Support for AdditionalInfos (on CEMI) added
* Renamed `DataPointType#getRawData()` to `DataPointType#toByteArray()` to be consistent with `DataPointValue`
* Log level has been revised at some places and raw data is not always printed for every cases anymore (-> noise reduction)
* New documentation section for KNX examples
* I also added `CEMIAware` interface, which you will like as it will allow:
```
before:
if (item is TunnelingRequestBody) {
    val data = item.getCEMI().getData();
    ... do something with data ...
} else if (item is RoutingIndicationBody) {
    val data = item.getCEMI().getData();
    ... do something with data ...
}

now:
if (item is CEMIAware) {
    val data = item.getCEMI().getData();
    ... do something with data ...
}
```

If you have some DPTs which should be added, let me know it. This is a good time to mention it as I am planning to add more DPTs in next time.

**Comment by StefanOltmann** [comment]
Hi Christoph.

Great news. 👍 

Unfortunately since logging with the Audit plugin this error did not occur again. I really do not know what communication on the bus may have caused it.

You covered all DPTs I'm aware of in my system so far.

And of course I'll do a long term test with version 0.3. :)

Closing this issue as the problem is not reproducible right now.
